// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using deepduplicates;

namespace deepduplicates.Migrations
{
    [DbContext(typeof(VideoInfoContext))]
    [Migration("20191225220126_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("deepduplicates.VideoInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("fileHash")
                        .HasColumnType("TEXT");

                    b.Property<long?>("fileSize")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("image1Checksum")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("image2Checksum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("path")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("VideoInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
