// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using deepduplicates;

namespace deepduplicates.Migrations
{
    [DbContext(typeof(VideoInfoContext))]
    partial class VideoInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("deepduplicates.VideoInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("fileHash")
                        .HasColumnType("TEXT");

                    b.Property<long?>("fileSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("formatNotSupported")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("image1Checksum")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("image1hash_blob")
                        .HasColumnType("BLOB");

                    b.Property<long?>("image2Checksum")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("image2hash_blob")
                        .HasColumnType("BLOB");

                    b.Property<long?>("image3Checksum")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("image3hash_blob")
                        .HasColumnType("BLOB");

                    b.Property<string>("path")
                        .HasColumnType("TEXT");

                    b.Property<string>("reason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("remove")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("VideoInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
